# frozen_string_literal: true
$VERBOSE = nil
require 'open3'
require 'pod/command/publish'
require 'cocoapods-publish/pod_utils'
require 'cocoapods-publish/podfile_dsl'
require 'cocoapods-publish/repo_utils'
require 'cocoapods-publish/gitlab_utils'
require 'hooks/auto_switch_source_hook'
require 'hooks/analyzer'
require 'hooks/installer'
require 'hooks/install_command'
require 'hooks/version'
require 'hooks/dependency'
require 'hooks/podfile'
require 'hooks/project'
